json.id beer.id
json.name beer.name
json.description beer.description
json.price beer.price 
json.in_stock beer.in_stock
json.tax beer.tax
json.total beer.total
json.discount? beer.is_discounted
json.images beer.photo_url
json.supplier_ID beer.supplier_id
json.supplier beer.supplier_info