json.Beer_ID beer.id
json.Beer_name beer.name
json.Beer_description beer.description
json.Beer_price beer.price 
json.Beer_in_stock beer.in_stock
json.Beer_tax beer.tax
json.Beer_total beer.total
json.Beer_discount? beer.is_discounted
json.Beer_images beer.photo_url
json.Beer_supplier_ID beer.supplier_id
json.Beer_supplier beer.supplier_info